/// Categoría del catálogo inicial (todavía sin id).
class CategorySeed {
  const CategorySeed(
    this.name, {
    required this.isIncome,
    required this.isFixed,
    this.isAntExpense = false,
    required this.iconKey,
    required this.colorHex,
    required this.groupLabel,
  });

  final String name;
  final bool isIncome;
  final bool isFixed;
  final bool isAntExpense;
  final String iconKey;
  final String colorHex;
  final String groupLabel;
}

/// Catálogo inicial. Se crea una sola vez, al terminar la bienvenida.
/// El orden de la lista es el orden en que se muestran por defecto.
const List<CategorySeed> defaultCategorySeeds = [
  // --- Catálogo original ---
  CategorySeed(
    'Salario',
    isIncome: true,
    isFixed: true,
    iconKey: 'work',
    colorHex: '#2E9E5B',
    groupLabel: 'Ingresos Fijos',
  ),
  CategorySeed(
    'Ingresos adicionales',
    isIncome: true,
    isFixed: false,
    iconKey: 'add_card',
    colorHex: '#5BBF85',
    groupLabel: 'Ingresos Variables y Extras',
  ),
  CategorySeed(
    'Arriendo',
    isIncome: false,
    isFixed: true,
    iconKey: 'home',
    colorHex: '#1E6FD9',
    groupLabel: 'Gastos Fijos',
  ),
  CategorySeed(
    'EPM',
    isIncome: false,
    isFixed: true,
    iconKey: 'bolt',
    colorHex: '#F2A900',
    groupLabel: 'Gastos Fijos',
  ),
  CategorySeed(
    'FNA',
    isIncome: false,
    isFixed: true,
    iconKey: 'account_balance',
    colorHex: '#6C5CE7',
    groupLabel: 'Gastos Fijos',
  ),
  CategorySeed(
    'JFK',
    isIncome: false,
    isFixed: true,
    iconKey: 'payments',
    colorHex: '#00A6A6',
    groupLabel: 'Gastos Fijos',
  ),
  CategorySeed(
    'Internet',
    isIncome: false,
    isFixed: true,
    iconKey: 'wifi',
    colorHex: '#3D8BFD',
    groupLabel: 'Gastos Fijos',
  ),
  CategorySeed(
    'TV',
    isIncome: false,
    isFixed: true,
    iconKey: 'tv',
    colorHex: '#8E5CF7',
    groupLabel: 'Gastos Fijos',
  ),
  CategorySeed(
    'GYM',
    isIncome: false,
    isFixed: true,
    iconKey: 'fitness_center',
    colorHex: '#E8590C',
    groupLabel: 'Gastos Fijos',
  ),
  CategorySeed(
    'Mercado',
    isIncome: false,
    isFixed: false,
    iconKey: 'shopping_cart',
    colorHex: '#2F9E44',
    groupLabel: 'Gastos Variables',
  ),
  CategorySeed(
    'Transporte',
    isIncome: false,
    isFixed: false,
    iconKey: 'directions_bus',
    colorHex: '#1C7ED6',
    groupLabel: 'Gastos Variables',
  ),
  CategorySeed(
    'Ropa',
    isIncome: false,
    isFixed: false,
    iconKey: 'checkroom',
    colorHex: '#D6336C',
    groupLabel: 'Gastos Variables',
  ),
  CategorySeed(
    'Mecatos',
    isIncome: false,
    isFixed: false,
    isAntExpense: true,
    iconKey: 'fastfood',
    colorHex: '#F76707',
    groupLabel: 'Hormiga y Fantasma',
  ),
  CategorySeed(
    'Otras D',
    isIncome: false,
    isFixed: false,
    isAntExpense: true,
    iconKey: 'more_horiz',
    colorHex: '#868E96',
    groupLabel: 'Hormiga y Fantasma',
  ),

  // --- Ingresos Fijos ---
  CategorySeed(
    'Salario base (Sueldo neto)',
    isIncome: true,
    isFixed: true,
    iconKey: 'work',
    colorHex: '#2E9E5B',
    groupLabel: 'Ingresos Fijos',
  ),
  CategorySeed(
    'Honorarios profesionales fijos',
    isIncome: true,
    isFixed: true,
    iconKey: 'account_balance_wallet',
    colorHex: '#2E9E5B',
    groupLabel: 'Ingresos Fijos',
  ),
  CategorySeed(
    'Pensiones o jubilación',
    isIncome: true,
    isFixed: true,
    iconKey: 'elderly',
    colorHex: '#2E9E5B',
    groupLabel: 'Ingresos Fijos',
  ),

  // --- Ingresos Variables y Extras ---
  CategorySeed(
    'Comisiones y bonos',
    isIncome: true,
    isFixed: false,
    iconKey: 'percent',
    colorHex: '#00A6A6',
    groupLabel: 'Ingresos Variables y Extras',
  ),
  CategorySeed(
    'Horas extras',
    isIncome: true,
    isFixed: false,
    iconKey: 'more_time',
    colorHex: '#00A6A6',
    groupLabel: 'Ingresos Variables y Extras',
  ),
  CategorySeed(
    'Aguinaldo / Prima de vacaciones',
    isIncome: true,
    isFixed: false,
    iconKey: 'redeem',
    colorHex: '#00A6A6',
    groupLabel: 'Ingresos Variables y Extras',
  ),
  CategorySeed(
    'Devolución de impuestos',
    isIncome: true,
    isFixed: false,
    iconKey: 'receipt_long',
    colorHex: '#00A6A6',
    groupLabel: 'Ingresos Variables y Extras',
  ),

  // --- Trabajos Secundarios ---
  CategorySeed(
    'Ventas de productos o servicios freelance',
    isIncome: true,
    isFixed: false,
    iconKey: 'storefront',
    colorHex: '#8E5CF7',
    groupLabel: 'Trabajos Secundarios',
  ),
  CategorySeed(
    'Venta de artículos usados',
    isIncome: true,
    isFixed: false,
    iconKey: 'sell',
    colorHex: '#8E5CF7',
    groupLabel: 'Trabajos Secundarios',
  ),

  // --- Ingresos Pasivos ---
  CategorySeed(
    'Intereses y rendimientos (Plazos fijos, fondos)',
    isIncome: true,
    isFixed: false,
    iconKey: 'account_balance',
    colorHex: '#1E6FD9',
    groupLabel: 'Ingresos Pasivos',
  ),
  CategorySeed(
    'Dividendos de inversiones',
    isIncome: true,
    isFixed: false,
    iconKey: 'pie_chart',
    colorHex: '#1E6FD9',
    groupLabel: 'Ingresos Pasivos',
  ),
  CategorySeed(
    'Rentas y alquileres cobrados',
    isIncome: true,
    isFixed: false,
    iconKey: 'apartment',
    colorHex: '#1E6FD9',
    groupLabel: 'Ingresos Pasivos',
  ),

  // --- Gastos Fijos ---
  CategorySeed(
    'Vivienda',
    isIncome: false,
    isFixed: true,
    iconKey: 'home',
    colorHex: '#1E6FD9',
    groupLabel: 'Gastos Fijos',
  ),
  CategorySeed(
    'Servicios Públicos',
    isIncome: false,
    isFixed: true,
    iconKey: 'bolt',
    colorHex: '#1E6FD9',
    groupLabel: 'Gastos Fijos',
  ),
  CategorySeed(
    'Alimentación',
    isIncome: false,
    isFixed: true,
    iconKey: 'shopping_cart',
    colorHex: '#1E6FD9',
    groupLabel: 'Gastos Fijos',
  ),
  CategorySeed(
    'Transporte Obligatorio',
    isIncome: false,
    isFixed: true,
    iconKey: 'directions_bus',
    colorHex: '#1E6FD9',
    groupLabel: 'Gastos Fijos',
  ),
  CategorySeed(
    'Salud y Seguros',
    isIncome: false,
    isFixed: true,
    iconKey: 'local_hospital',
    colorHex: '#1E6FD9',
    groupLabel: 'Gastos Fijos',
  ),
  CategorySeed(
    'Educación',
    isIncome: false,
    isFixed: true,
    iconKey: 'school',
    colorHex: '#1E6FD9',
    groupLabel: 'Gastos Fijos',
  ),

  // --- Deudas ---
  CategorySeed(
    'Tarjetas de Crédito',
    isIncome: false,
    isFixed: true,
    iconKey: 'credit_card',
    colorHex: '#D64545',
    groupLabel: 'Deudas',
  ),
  CategorySeed(
    'Préstamos Personales',
    isIncome: false,
    isFixed: true,
    iconKey: 'payments',
    colorHex: '#D64545',
    groupLabel: 'Deudas',
  ),
  CategorySeed(
    'Créditos Vehiculares o Educativos',
    isIncome: false,
    isFixed: true,
    iconKey: 'directions_car',
    colorHex: '#D64545',
    groupLabel: 'Deudas',
  ),
  CategorySeed(
    'Financiamientos a Plazos',
    isIncome: false,
    isFixed: true,
    iconKey: 'local_mall',
    colorHex: '#D64545',
    groupLabel: 'Deudas',
  ),

  // --- Gastos Variables ---
  CategorySeed(
    'Ocio y Entretenimiento',
    isIncome: false,
    isFixed: false,
    iconKey: 'movie',
    colorHex: '#F2A900',
    groupLabel: 'Gastos Variables',
  ),
  CategorySeed(
    'Restaurantes',
    isIncome: false,
    isFixed: false,
    iconKey: 'restaurant',
    colorHex: '#F2A900',
    groupLabel: 'Gastos Variables',
  ),
  CategorySeed(
    'Cuidado Personal',
    isIncome: false,
    isFixed: false,
    iconKey: 'spa',
    colorHex: '#F2A900',
    groupLabel: 'Gastos Variables',
  ),
  CategorySeed(
    'Regalos',
    isIncome: false,
    isFixed: false,
    iconKey: 'card_giftcard',
    colorHex: '#F2A900',
    groupLabel: 'Gastos Variables',
  ),

  // --- Hormiga y Fantasma ---
  CategorySeed(
    'Antojos Diarios',
    isIncome: false,
    isFixed: false,
    isAntExpense: true,
    iconKey: 'local_cafe',
    colorHex: '#E8590C',
    groupLabel: 'Hormiga y Fantasma',
  ),
  CategorySeed(
    'Suscripciones Digitales',
    isIncome: false,
    isFixed: false,
    isAntExpense: true,
    iconKey: 'subscriptions',
    colorHex: '#E8590C',
    groupLabel: 'Hormiga y Fantasma',
  ),
  CategorySeed(
    'Comida a Domicilio',
    isIncome: false,
    isFixed: false,
    isAntExpense: true,
    iconKey: 'delivery_dining',
    colorHex: '#E8590C',
    groupLabel: 'Hormiga y Fantasma',
  ),
  CategorySeed(
    'Transporte por Comodidad',
    isIncome: false,
    isFixed: false,
    isAntExpense: true,
    iconKey: 'local_taxi',
    colorHex: '#E8590C',
    groupLabel: 'Hormiga y Fantasma',
  ),
  CategorySeed(
    'Otros gastos hormiga',
    isIncome: false,
    isFixed: false,
    isAntExpense: true,
    iconKey: 'more_horiz',
    colorHex: '#E8590C',
    groupLabel: 'Hormiga y Fantasma',
  ),

  // --- Ahorro e Inversión ---
  CategorySeed(
    'Fondo de Emergencia',
    isIncome: false,
    isFixed: false,
    iconKey: 'savings',
    colorHex: '#2F9E44',
    groupLabel: 'Ahorro e Inversión',
  ),
  CategorySeed(
    'Ahorro con Propósito',
    isIncome: false,
    isFixed: false,
    iconKey: 'flag',
    colorHex: '#2F9E44',
    groupLabel: 'Ahorro e Inversión',
  ),
  CategorySeed(
    'Inversiones',
    isIncome: false,
    isFixed: false,
    iconKey: 'trending_up',
    colorHex: '#2F9E44',
    groupLabel: 'Ahorro e Inversión',
  ),
  CategorySeed(
    'Provisiones Anuales',
    isIncome: false,
    isFixed: false,
    iconKey: 'event_repeat',
    colorHex: '#2F9E44',
    groupLabel: 'Ahorro e Inversión',
  ),
];
